; DefaultGame.ini — Game-level configuration for MimicFacility

[/Script/EngineSettings.GeneralProjectSettings]
ProjectID=MimicFacility
ProjectName=MimicFacility
CompanyName=HoleInWater
Homepage=
SupportContact=
CopyrightNotice=Copyright (c) 2026 HoleInWater
ProjectVersion=0.1.0
ProjectDisplayedTitle=MimicFacility
ProjectDebugTitleInfo=MimicFacility (Debug)
bShouldWindowPreserveAspectRatio=True
bUseBorderlessWindow=False
bStartInVR=False
bAllowWindowResize=True
bAllowClose=True
bAllowMaximize=True
bAllowMinimize=True
